name: Terraform Dev Check
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    permissions:
      contents: read # Allow the workflow to read the repository's content
      actions: none        # Not managing workflows
      checks: none         # Not creating/updating check runs directly
      deployments: none    # Not creating/managing deployments
      discussions: none    # Not interacting with discussions
      id-token: none       # You're using 'creds' for Azure, not OIDC. If you switch to OIDC, this would be 'write'.
      issues: none         # Not managing issues
      packages: none       # Not managing GitHub Packages
      pages: none          # Not managing GitHub Pages
      pull-requests: none  # Explicitly deny, as you commented out 'write' (prevents commenting, status updates)
      repository-projects: none # Not managing project boards
      security-events: none # Not uploading security scanning results (e.g., SARIF)
      statuses: none       # Not setting commit statuses directly (separate from PR status checks)

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v1
      - run: tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

