name: Terraform Dev Check
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    permissions:
      contents: read # Allow the workflow to read the repository's content
      #pull-requests: write # Allow the workflow to comment on PRs or update PR status

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v1
      - run: tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

